/**
 * Autogenerated; do not edit! Run "npm gen-types" to regenerate.
 *
 * This is a bit of a hack: WebStorm doesn't full recognize all Flow types, but
 * it matches types by name, so we can refine types to be more WebStorm-friendly
 * by including this file in the project.
 */

type Action = {
    match<T>(visitor: ActionVisitor<T>): T,
};

type Expression = {
    match<T>(visitor: ExpressionVisitor<T>): T,
};

type EvalExpression = {
    match<T>(visitor: EvalExpressionVisitor<T>): T,
};

type UserExpression = {
    match<T>(visitor: UserExpressionVisitor<T>): T,
};

type DisplayExpression = {
    match<T>(visitor: DisplayExpressionVisitor<T>): T,
};

type ExprContainer = {
    match<T>(visitor: ExprContainerVisitor<T>): T,
};

type DragResult = {
    match<T>(visitor: DragResultVisitor<T>): T,
};

type DropResult = {
    match<T>(visitor: DropResultVisitor<T>): T,
};

type ViewKey = {
    match<T>(visitor: ViewKeyVisitor<T>): T,
};

